In [91]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [131]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [150]:
torch.manual_seed(0)

T1 = torch.rand((7, 7))
T2 = torch.rand((1, 7))

In [151]:
T1 @ T2.T

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [159]:
torch.manual_seed(1234)

T3 = torch.rand((2, 3)).to(device)
T4 = torch.rand((2, 3)).to(device)

In [162]:
mul = T3 @ T4.T
mul

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [165]:
mul.max(), mul.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [166]:
mul.argmax(), mul.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [172]:
torch.manual_seed(7)

T5 = torch.rand((1, 1, 1, 10))
T5, T5.shape, T5.squeeze().shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))